# Generated by Django 3.2 on 2023-02-25 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('class_name', models.CharField(max_length=20, null=True)),
                ('class_fee', models.CharField(default=0, max_length=20, null=True)),
                ('class_fee_inst', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('department_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hostel_name', models.CharField(max_length=20, null=True)),
                ('hostel_fee', models.CharField(default=0, max_length=20, null=True)),
                ('hostel_fee_inst', models.CharField(max_length=20, null=True)),
                ('hostel_instruction', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('section_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admissions_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('admission_date', models.DateField()),
                ('admission_no', models.CharField(max_length=20, null=True)),
                ('roll_no', models.CharField(max_length=200, null=True)),
                ('caste', models.CharField(max_length=200, null=True)),
                ('religion', models.CharField(max_length=200, null=True)),
                ('father_occupation', models.CharField(max_length=100, null=True)),
                ('father_qualification', models.CharField(max_length=100, null=True)),
                ('mother_occupation', models.CharField(max_length=100, null=True)),
                ('mother_qualification', models.CharField(max_length=100, null=True)),
                ('alternate_mobile_no', models.CharField(max_length=100, null=True)),
                ('studentImage', models.ImageField(null=True, upload_to='static/images')),
                ('studentAadhar', models.ImageField(null=True, upload_to='static/images')),
                ('studentDOBCerficate', models.ImageField(null=True, upload_to='static/images')),
                ('studentTC', models.ImageField(null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='BusRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bus_name', models.CharField(max_length=50, null=True)),
                ('root_name', models.CharField(max_length=50, null=True)),
                ('root_fee', models.CharField(default=0, max_length=20, null=True)),
                ('root_inst', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('school_name', models.CharField(max_length=100, null=True)),
                ('school_address1', models.CharField(max_length=500, null=True)),
                ('school_address2', models.CharField(max_length=500, null=True)),
                ('school_mobile1', models.CharField(max_length=12, null=True)),
                ('school_mobile2', models.CharField(max_length=12, null=True)),
                ('school_email', models.EmailField(max_length=50, null=True)),
                ('school_web', models.CharField(max_length=100, null=True)),
                ('school_img', models.ImageField(null=True, upload_to='static/images')),
                ('school_logo', models.ImageField(null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Student_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student_type_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(null=True)),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('father_mobile_no', models.CharField(max_length=100, null=True)),
                ('mother_mobile_no', models.CharField(max_length=100, null=True)),
                ('temp_address', models.TextField(max_length=5000, null=True)),
                ('permanent_address', models.TextField(max_length=5000, null=True)),
                ('testDate', models.DateField(null=True)),
                ('testTime', models.DateTimeField(null=True)),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='ERP_app.addclass')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=50, null=True)),
                ('fee_amount', models.CharField(default=0, max_length=200, null=True)),
                ('month', models.CharField(max_length=20, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraFeeStructure', to='ERP_app.addclass')),
                ('student_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraFeeStructure', to='ERP_app.student_type')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraFeeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(max_length=50, null=True)),
                ('month', models.CharField(max_length=50, null=True)),
                ('main_amount', models.CharField(max_length=500, null=True)),
                ('discounted_amount', models.CharField(max_length=500, null=True)),
                ('final_amount', models.CharField(max_length=50, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('admission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraFeeDiscount', to='ERP_app.admissions_form')),
                ('extra_fee_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraFeeDiscount', to='ERP_app.extrafeestructure')),
            ],
        ),
        migrations.AddField(
            model_name='admissions_form',
            name='bus_root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='ERP_app.busroot'),
        ),
        migrations.AddField(
            model_name='admissions_form',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='ERP_app.addhostel'),
        ),
        migrations.AddField(
            model_name='admissions_form',
            name='reception',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='ERP_app.reception'),
        ),
        migrations.AddField(
            model_name='admissions_form',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='ERP_app.addsection'),
        ),
        migrations.AddField(
            model_name='admissions_form',
            name='student_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='ERP_app.student_type'),
        ),
        migrations.CreateModel(
            name='AddStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('mobile_no', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('joining_date', models.DateField(auto_now_add=True, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('basic_salary', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('husband_name', models.CharField(max_length=100, null=True)),
                ('staff_qualification', models.CharField(max_length=100, null=True)),
                ('temp_address', models.TextField(max_length=5000, null=True)),
                ('permanent_address', models.TextField(max_length=5000, null=True)),
                ('alternate_mobile_no', models.CharField(max_length=100, null=True)),
                ('staffImage', models.ImageField(null=True, upload_to='static/images')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addstaff', to='ERP_app.adddepartment')),
            ],
        ),
    ]
