# Generated by Django 3.2 on 2023-02-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0005_busfeediscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelExtraFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=50, null=True)),
                ('fee_amount', models.CharField(default=0, max_length=200, null=True)),
                ('month', models.CharField(max_length=20, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('student_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostelExtraFeeStructure', to='ERP_app.student_type')),
            ],
        ),
    ]
