# Generated by Django 3.2 on 2023-03-11 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0009_auto_20230226_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt_for_ExtraFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('extra_fee_name', models.CharField(max_length=500, null=True)),
                ('extra_fee', models.CharField(max_length=500, null=True)),
                ('discounted_extra_fee', models.CharField(default=0, max_length=500, null=True)),
                ('payable_extra_fee', models.CharField(max_length=500, null=True)),
                ('paid_extra_fee', models.CharField(max_length=500, null=True)),
                ('extra_fee_dues', models.CharField(max_length=500, null=True)),
                ('extra_fee_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_for_extraFee', to='ERP_app.extrafeestructure')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_for_extraFee', to='ERP_app.receipt')),
            ],
        ),
    ]
