# Generated by Django 3.2 on 2023-03-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0011_auto_20230311_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeediscount',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
