# Generated by Django 3.2 on 2023-03-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0014_extrafeediscount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='previous_paid_amount',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
