# Generated by Django 3.2 on 2023-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0018_rename_previous_bill_paid_amount_receipt_previous_bill_current_month_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelextrafeediscount',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hostelfeediscount',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
