# Generated by Django 3.2 on 2023-03-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0019_auto_20230318_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('receipt_name', models.CharField(max_length=50, null=True)),
                ('month', models.CharField(max_length=50, null=True)),
                ('issued_by', models.CharField(max_length=50, null=True)),
                ('hostel_fee', models.CharField(max_length=500, null=True)),
                ('discounted_hostel_fee', models.CharField(max_length=500, null=True)),
                ('hoste_payable_fee', models.CharField(max_length=500, null=True)),
                ('hoste_paid_fee', models.CharField(max_length=500, null=True)),
                ('hoste_dues', models.CharField(max_length=500, null=True)),
                ('total_amount', models.CharField(max_length=500, null=True)),
                ('total_discounted_amount', models.CharField(max_length=500, null=True)),
                ('total_payble_amount', models.CharField(max_length=500, null=True)),
                ('previous_bill_current_month_paid_amount', models.CharField(default=0, max_length=500, null=True)),
                ('paid_amount', models.CharField(max_length=500, null=True)),
                ('total_dues', models.CharField(max_length=500, null=True)),
                ('admission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_receipt', to='ERP_app.admissions_form')),
                ('hostel_fee_discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='ERP_app.hostelextrafeediscount')),
            ],
        ),
    ]
