# Generated by Django 3.2 on 2023-03-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0020_hostel_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel_receipt',
            old_name='hoste_dues',
            new_name='hostel_dues',
        ),
        migrations.RenameField(
            model_name='hostel_receipt',
            old_name='hoste_paid_fee',
            new_name='hostel_paid_fee',
        ),
        migrations.RenameField(
            model_name='hostel_receipt',
            old_name='hoste_payable_fee',
            new_name='hostel_payable_fee',
        ),
    ]
