# Generated by Django 3.2 on 2023-03-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0021_auto_20230318_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_receipt',
            name='hostel_fee_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_receipt', to='ERP_app.hostelextrafeediscount'),
        ),
    ]
