# Generated by Django 3.2 on 2023-04-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0024_reception_date_of_enq'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissions_form',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
