# Generated by Django 3.2 on 2023-04-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0026_auto_20230426_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
