# Generated by Django 3.2 on 2023-05-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0029_addhostel_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroot',
            name='year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
