# Generated by Django 3.2 on 2023-05-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_app', '0030_busroot_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstaff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
